# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.

title: George Akor - Portfolio & Blog
description: >-
  Personal portfolio and blog of George Akor - Software Engineer, Graduate Researcher (AI, Smart Contracts).
baseurl: "/georgeakorai"
url: "https://jupiter-plantagenet.github.io"

# Build settings
markdown: kramdown
theme: minima # Using a basic theme for now, can be customized
plugins:
  - jekyll-feed

collections:
  projects:
    output: true
    permalink: /projects/:name/

# show posts with future dates
future: true
livereload: false

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
